### ISSUE TITLE
[Bug]: Cuando busco una pagina que no existe con search me devuelve null y statusCode 500

### ISSUE THREAD

**Issue by josueBarretogit** [PORTADA-INMOBILIARIA-SAS/php-api-v1.1#3]
### What happened?

Llamo a este endpoint `https://portadainmobiliaria.cloud/api/v1.1/pqrs/?search=ventas&limit=2&page=2` y page 2 no existe debería recibir una array vacio y un statusCode 404, pero eso me devuelve un statusCode 500 y null

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JohnGolgota** [comment]
Entre los planes de despliegue de pqrs, esta cubrir la utilidad de este api con el proyecto: [Apis-CRINMO](https://github.com/PORTADA-INMOBILIARIA-SAS/Apis-CRINMO)

quiero decir esto se archiva.

**Comment by josueBarretogit** [comment]
RIP api de steban

**Comment by JohnGolgota** [comment]
> RIP api de steban

Gracias al cielo. No me gusto hacer esto en PHP
